### ISSUE TITLE
Twitter::Validation.valid_url? rejects URLs with unicode paths

### ISSUE THREAD

**Issue by samuel** [twitter-archive/twitter-text-rb#13]
A real world URL that fails:

http://www.amazon.com/Jeanne-Córdova/e/B001KC61FK/ref=cm_sw_r_tw_nu_7-WQob0RDA65Y

To better see the unicode character here it is quoted:

http%3A%2F%2Fwww.amazon.com%2FJeanne-C%C3%B3rdova%2Fe%2FB001KC61FK%2Fref%3Dcm_sw_r_tw_nu_7-WQob0RDA65Y

A test that verifies this:

``` yaml
    - description: "Valid unicode url: unicode path"
      text: "http://www.example.com/Bob-Córdova/"
      expected: true
```
